### ISSUE TITLE
Update HYSPEC geometry for polarization mirrors

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantidgeometry#68]
Barry sent out the document with the equations, but here are the names for the virtual motors to make the whole thing work.

For HYSPEC, using legacy motors, please add two virtual nonmoving motors to both the satellite app and the CPA:

`PSDA`:  polarizing supermirror deflection angle (deg), default value 0 deg
`PSR`:  polarizing supermirror radius (mm), default value 635 mm

We don’t need them until the 2015A cycle, so no need to stop by HYSPEC this week.

**Comment by AndreiSavici** [comment]
The value of `PSDA` is unreliable (user input, not read from motor). Also, this would involve creating a new value for `s1`, since the current geometry does not support adding more than one log into a position in IDF. The current way of using `RotateInstrumentComponent` is working, and instrument scientists are happy with that
